### ISSUE TITLE
vmlinux_file is not populated in builds

### ISSUE THREAD

**Issue by mattface** [kernelci/kernelci-backend#1]
As described here:
https://api.kernelci.org/schema-build.html
and I'm calling
https://api.kernelci.org/build?job=next&kernel=next-20160511&status=PASS&arch=arm

For builds where a vmlinux is produced (such as defconfig arm-stm32_defconfig), kernel_image is None and vmlinux_file is not available in the API response, so I have no way of getting a kernel from the API for this type of build.
The files were successfully published by Kevins builder:
https://storage.kernelci.org/next/next-20160511/arm-stm32_defconfig/

Do we need to have a difference between kernel_image and vmlinux_file anyway? It's tedious to code around.

**Comment by MiloCasagrande** [comment]
The vmlinux file is only used to extract ELF related information, it will be deleted lately by the backend.
If the build is PASS and there is no kernel_image defined, that should be a problem. It needs to be seen what is happening on the build side.

vmlinux_file will be dropped, everything should be in kernel_image.

**Comment by mattface** [comment]
Ah, ok so maybe that defconfig doesnt produce anything other than a vmlinux file. In fact it seems to need "make xipimage" to produce a kernel image called "xipImage".

The old job creator only looks for files called Image, zImage or bzImage, so probably just close this bug and I'll just ignore any builds with kernel_image = None.

**Comment by khilman** [comment]
Looks like a bug in build.py.

The kernel build process is generating the xipImage, it's just not making it into the "installed" results.

**Comment by khilman** [comment]
Fixed:
https://github.com/kernelci/kernelci-build/commit/1ab3aa6e06b4b00fcaeaa160aa40d30d467c3ea1

**Comment by mattface** [comment]
Nice one. Closing this issue.
