### ISSUE TITLE
Would you please kindly tell us  what operation system you are working on?

### ISSUE THREAD

**Issue by lookatcn** [kernelci/kernelci-backend#10]
Hi,

We are trying to set up local kernelci-backend.
But we are experiencing some problems on ubuntu 14.04.
Would you please kindly tell us  what operation system you are working on ? 

Thank you!

**Comment by MiloCasagrande** [comment]
We run kernelci.org on Debian 8.7 (Jessie).

**Comment by lookatcn** [comment]
Thank you!
