### ISSUE TITLE
dtb link incorrect on boot page

### ISSUE THREAD

**Issue by danrue** [kernelci/kernelci-backend#131]
On the following page, the dtb link is incorrect: https://kernelci.org/boot/id/5cc67ba059b51490585584ca/

The link labeled "qcom/apq8016-sbc.dtb" leads to https://storage.kernelci.org/mainline/master/v5.1-rc7/arm64/defconfig/gcc-7/qcom/apq8016-sbc.dtb which yields a 404 Not Found.

Rather, it should point to https://storage.kernelci.org/mainline/master/v5.1-rc7/arm64/defconfig/gcc-7/dtbs/qcom/apq8016-sbc.dtb.

The missing bits seem to be the extra '/dtbs/' path in the url.

**Comment by khilman** [comment]
In the lava /boot callback, looks like we're somehow dropping the `dtbs` part of the path.   Investigating.

**Comment by gctucker** [comment]
Boot tests have been dropped.  The DTB links on test case pages appear to be correct, for example:
https://kernelci.org/test/case/id/5f6b41b18457d6e6b9bf9ddc/
https://storage.kernelci.org/media/master/v5.9-rc4-362-g01cc2ec6ea04/arm64/defconfig+virtualvideo/gcc-8/dtbs/broadcom/bcm2711-rpi-4-b.dtb
