### ISSUE TITLE
Rework boot report POST API

### ISSUE THREAD

**Issue by MiloCasagrande** [kernelci/kernelci-backend#4]
We should rework how we import and save the boot report and how we look for "unique" values in the boot report.

Right now, the boot report is imported asynchronously and the API will return a 202 status, and eventually import the data. If somebody sends another boot report with the same "unique" fields, we consider that boot report an updated version.

We need to change this behavior and:
* At POST-time, return the future ID the boot report will have (through a Location header), and simply import the data (upon validation).
* Treat each POST requests as unique boot reports.
* Make sure we have PUT or PATCH API in place to enable update of a single boot report via its ID value.

**Comment by gctucker** [comment]
Boot email reports are not sent any more.  There is no such issue with the test email reports.
