### ISSUE TITLE
Boot warnings is a count, not a free text form field

### ISSUE THREAD

**Issue by MiloCasagrande** [kernelci/kernelci-backend#46]
Not sure when this started, but some boot reports are using the `warnings` fields to report warnings text, not number:

https://kernelci.org/boot/id/5a38cb7a59b51443d2afa187/

That's one, but there are many more.

**Comment by MiloCasagrande** [comment]
@gctucker FYI:

https://kernelci.org/boot/id/5a39da7a59b5145fbfafa16d/

the `warnings` field should be an integer.

I looked a little bit further if other labs where reporting the same, but it appears it's only Collabora lab. Not sure where this is happening though: LAVA import side...

Not sure if we want to cast that field to a number at import time (although it might be good) or do something else.

**Comment by gctucker** [comment]
I've compared the different LAVA versions in several labs:
lab-collabora: 2017.9 + some minor patches
lab-mhart: 2017.7
lab-baylibre-seattle: 2017.11.post1

although I'm not sure we're actually receiving any callback data from lab-baylibre-seattle.  So it may be something that changed between 2017.7 and 2017.9.  Will take a look at the code.

**Comment by gctucker** [comment]
OK there's a bug in kernelci-backend, it's actually putting the kernel warning messages in the warnings meta-data which then gets put into the boot document warnings field, in `utils/callback/lava.py`:

```
    if kernel_messages:
        meta[models.BOOT_WARNINGS_KEY] = kernel_messages
```

It should probably be putting `len(kernel_messages)` there instead, but I'm pretty sure there's also a place to store the actual warning messages.  Will take a look.

**Comment by MiloCasagrande** [comment]
On Thu, Dec 21, 2017 at 10:50 AM, Guillaume Tucker
<notifications@github.com> wrote:
>
> OK there's a bug in kernelci-backend, it's actually putting the kernel warning messages in the warnings meta-data which then gets put into the boot document warnings field, in utils/callback/lava.py:
>
>     if kernel_messages:
>         meta[models.BOOT_WARNINGS_KEY] = kernel_messages
>
> It should probably be putting len(kernel_messages) there instead, but I'm pretty sure there's also a place to store the actual warning messages. Will take a look.


Thanks.

I don't think we have a place to store the boot logs warning messages
though (other than the boot log txt and html files).
We do that for builds when parsing the build logs.

-- 
Milo Casagrande <milo@opensourcefoundries.com>
