### ISSUE TITLE
timeout with GET /test/case

### ISSUE THREAD

**Issue by khilman** [kernelci/kernelci-backend#49]
Need help understanding where the timeout comes from when doing a GET on /test/case.  @MiloCasagrande could you help point to where those timeouts are?

**Comment by MiloCasagrande** [comment]
I just tried a few times, both internally on the server and locally on my machine, but I can't reproduce this issue.

The first time I run the query, it took something like 12 seconds to extract and return all the data, but afterwards it was cached. It could be that you hit the proxy timeout between nginx and the actual kernelci process. Do you remember what was the output you got?

Remember though that querying `/test/case` will return **all** test cases, and that is around 140 MB of uncompressed text.

**Comment by khilman** [comment]
The tool being tested got a `504 Gateway Time Out`
Could you share your example script (or curl cmdline) you used to test it directly?

**Comment by MiloCasagrande** [comment]
This is what I used, both from the server and my local machine:

curl -X GET -H "Authorization: $TOKEN" -H "Accept-Encoding: gzip"
"https://api.kernelci.org/test/case" > /tmp/test-cases.json
curl -X GET -H "Authorization: $TOKEN"
"https://api.kernelci.org/test/case" > /tmp/test-cases.json

The first command will give you a 4.5 MB file, the second a 140 MB one.
Ciao.

-- 
Milo Casagrande <milo@opensourcefoundries.com>

**Comment by khilman** [comment]
Closing as this seemed to only exist on an older install of kernelCI backend.
