### ISSUE TITLE
Add new "unique" fields to the boot report import to drop the rootfs type

### ISSUE THREAD

**Issue by MiloCasagrande** [kernelci/kernelci-backend#5]
Right now, when a boot report is imported, we cross-check if we have a similar boot report and in case we find one, consider the being-imported one as an updated version.

In order to find the correct boot report we have a list of fields that make the "unique" search.

In order to drop the rootfs type that is being added to the board name, we need to add new fields to make this "unique" search.

This is a temporary measure, since we want to update the way the boot POST API work as tracked in issue #4.

**Comment by gctucker** [comment]
This approach is now deprecated.  Instead, we're replacing boots with baseline tests which can have any number of test plan variants (i.e. baseline-nfs...) to keep the results separate in the database simply using the test plan name.
