### ISSUE TITLE
out of memory when filtering tests

### ISSUE THREAD

**Issue by mwasilew** [kernelci/kernelci-backend#69]
When requesting /test/case api with the following parameters:
```
params = {
        "test_suite_id": non_existing_suite_oid
    }
```
backend runs out of memory trying to reply to this request. Example code to trigger the problem
```
def get_testcases(suite_oid):
    headers = {
        "Authorization": AUTHORIZATION_TOKEN
    }

    params = {
        "test_suite_id": suite_oid
    }
    url = urljoin(BACKEND_URL, "/test/case/")
    response = requests.get(url, params=params, headers=headers)
    return response.json().get('result')
```

**Comment by mwasilew** [comment]
Actually the problem happens also with existing test_suite_id. I tried with various options:
 - only $oid
 - serialized {$oid: xxxxx}
 - dictionary {$oid: xxxxx}
Result is always the same - gateway timeout. Fortunately this time the backend didn't run out of memory.

**Comment by gctucker** [comment]
This was fixed by adding sensible indexes to the database collections, and by optimizing a few things in the code.
