### ISSUE TITLE
feature request: boot log txt -> html conversion

### ISSUE THREAD

**Issue by khilman** [kernelci/kernelci-backend#9]
Currently the labs are running a log2html.py script on boot logs and then uploading both the txt and html logs to the backend. 

Feature request: the backend could take the .txt and convert it to html if html is not uploaded by the lab.

**Comment by mattface** [comment]
This would be handy because I haven't yet bothered to generate the html logs for v2

**Comment by MiloCasagrande** [comment]
This is actually being worked with pull request #11, although only for the LAVA v2 jobs.

**Comment by gctucker** [comment]
@khilman Can we close this now that it's working for LAVA v2 or do we care about converting other boot logs? (non-LAVA maybe)
