### ISSUE TITLE
Issue with builds not being visible 

### ISSUE THREAD

**Issue by RobertAJMarshall** [kernelci/kernelci-backend#94]
I reported this issue https://gitlab.com/cip-project/cip-testing/testing/issues/203 via IRC - and it was left with me IIRC - from this evening I shall have retired(!) so am unlikely to be doing much more investigation. But will leave that here as the issue is still replicable.

**Comment by gctucker** [comment]
Thanks for reporting this, I made the change and didn't see any issue with it but I'll investigate and try to reproduce what you've found.

**Comment by gctucker** [comment]
This issue can't be reproduced, all the builds are available via the web interface on kernelci.org.
